### ISSUE TITLE
How to use the `-tags="divert_embedded"`

### ISSUE THREAD

**Issue by orestonce** [imgk/divert-go#3]
I change the `example/version-info/main.go` to [this](https://go.dev/play/p/126AskZtv2m), and build by command:
````
go build -tags="divert_embedded"
````
then I run version-info.exe, error happend: 
````
 .\version-info.exe
panic: Unable to find "WinDivert.dll" RCDATA resource: The specified image file did not contain a resource section.

goroutine 1 [running]:
main.main()
````
* What should I do ?

**Comment by imgk** [comment]
Embed DLL files like wireguard-windows

https://github.com/WireGuard/wireguard-windows/blob/004c22c5647e5c492daf21d0310cbf575e4e3277/resources.rc#L17

**Comment by orestonce** [comment]
Thanks
